### ISSUE TITLE
Team Nayana- Firebase backend

### ISSUE THREAD

**Issue by hadiyarajesh** [NotesCommunity/easy-notes#10]
**Description**
We need to work on the tasks below to complete the entire backend side on firebase

**Tasks**
- [ ] Create DB and storage 
- [ ] Create REST API
- [ ] Add firebase specific things
