### ISSUE TITLE
Authentication and Notes

### ISSUE THREAD

**Issue by hadiyarajesh** [NotesCommunity/easy-notes#3]
**Description**
We need to work on below tasks to complete the authentication and notes creation/modification.

**Tasks**
- [ ] Allow users to authenticate with user
- [ ] Allow users to create notes
- [ ] Allow users to edit notes
